services:
  # =================================================
  # Aptible Tunnel Service (PostgreSQL + Redis + Terminal UI)
  # =================================================
  aptible-cli:
    build:
      context: .
      dockerfile: aptible/Dockerfile
    container_name: aptible-cli
    networks:
      - aptible-net
    ports:
      - "3080:3000"
      - "54324:54321"
      - "51598:51597"
    env_file:
      - ./aptible/.env
    volumes:
      - ./aptible-config:/home/aptible/.aptible  #persist aptible configuration
    tty: true
    stdin_open: true
    restart: unless-stopped
    mem_limit: 256m
    cpus: "0.25"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # =================================================
  # Backend Service (Java Spring Boot) example, 
  # should be in same docker network to access aptible-cli services (PostgreSQL, Redis)
  # =================================================
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   env_file:
  #     - ./backend/configuration/.env
  #   networks:
  #     - aptible-net
  #   depends_on:
  #     - aptible-cli
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

networks:
  aptible-net:
    driver: bridge
    name: aptible-net
